### STAGE 1: Build ###
FROM node:alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install

RUN npm install react-scripts -g

COPY ./ /app/

RUN npm run build


### STAGE 2: Production Environment ###
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g", "daemon off;"]
